script:
  enable: true
  local-jar-path: /Users/chinaPug/code/java/script-test/target
  remote-jar-url: /Users/chinaPug/code/java/script-test/target
  enabled-banner: true
  executor:
    - name: a
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 100
      keep-alive-seconds: 60
      task-rejected-policy: CALLER_RUNS
    - name: b
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 100
      keep-alive-seconds: 60
      task-rejected-policy: CALLER_RUNS

server:
  port: 8080
  reactive:
    session:
      timeout: 30m