script:
  enable: true
  local-jar-path: /Users/chinaPug/code/java/script-test/target
  enabled-banner: true
  log-config:
    log-dir: "logs/dynamic-task"
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n[File:%file Line:%line]%n"
  executor:
    - name: a
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 10
      keep-alive-seconds: 60

server:
  port: 8080
  reactive:
    session:
      timeout: 30m